name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, it seems to be the first time to commit issue, please commit the information to us as detailed as possible'
        pr-message: 'Hi, it seems to be the first time to commit pr, we will deal it as fast as possible'
